version: '3'

services:
  web:
    build:
      context: .
    depends_on:
      - redis
    links:
      - redis
    env_file:
      - ./env/dev.env
    ports:
      - "8001:8001"

  redis:
    image: redis:latest
    command: redis-server --appendonly yes
    volumes:
      - /docker/redis-dev-data:/data
