version: '3'

services:
  web:
    build:
      context: .
    volumes:
      - .:/devops_challenge
    depends_on:
      - redis
    env_file:
      - ./.env
    ports:
      - "8000:8000"

  redis:
    image: redis:latest
    command: redis-server --appendonly yes
    volumes:
      - ./data:/data
