version: '3'

services:
  web:
    build:
      context: .
    depends_on:
      - redis
    links:
      - redis
    env_file:
      - ./env/prod.env
    ports:
      - "8000:8000"

  redis:
    image: redis:latest
    command: redis-server --appendonly yes
    volumes:
      - /docker/redis-prod-data:/data
